# Generated by Django 4.1.1 on 2022-09-13 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockForecasting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockDataModel',
            new_name='StockData',
        ),
    ]
