# Generated by Django 4.1.1 on 2022-10-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockForecasting', '0002_rename_stockdatamodel_stockdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('ticker', models.CharField(max_length=5, verbose_name='Ticker')),
            ],
        ),
    ]
